GET http://localhost:5240/todos

###

POST http://localhost:5240/todos
content-type: application/json

{
  "id": 6,
  "name": "Write demo middle",
  "dueDate": "2027-12-31",
  "isCompleted": false
}

###

PUT http://localhost:5240/todos/5
content-type: application/json

{
  "id": 7,
  "name": "Write demo edit",
  "dueDate": "2023-12-31",
  "isCompleted": false
}

###

GET http://localhost:5240/todos/7

###
GET http://localhost:5240/tasks/7

###

DELETE http://localhost:5240/todos/6

###

DELETE http://localhost:5240/todos